#!/usr/bin/env bash
set -m
DIR="${0%/*}"

# Depth-first recursive kill
rkill() {
  local pids="$(pgrep -P "$1")"
  for subpid in $pids; do rkill "$subpid" 1; done
  if [[ "$2" == 1 ]]; then kill "$1" &>/dev/null; fi
}
finish() {
  rkill $$
}
trap finish EXIT SIGHUP SIGINT SIGTERM

#source "$DIR/actions/stop.sh"
ACTION="$1"

case "$1" in
  stop)
    source "$DIR/actions/stop.sh"
    ;;

  restart)
    source "$DIR/actions/stop.sh"
    source "$DIR/actions/start.sh"
    ;;

  start)
    source "$DIR/actions/start.sh"
    ;;

  *)
    echo "Usage: $0 <start|stop|restart>"
    exit 1
    ;;
esac
